### PR TITLE
Added a few battle names (previously placeholders)

### PR DESCRIPTION
**Pull request by LillianGoulston**
Added a few battle names to ModMenu.msg. Somehow ModMenu.flow was also changed to remove many extraneous spaces from the end of lines, but this shouldn't affect anything.

### CODE REVIEW

**Comment by LillianGoulston** [comment]
Added features for evolving Personas, choosing where to spawn in Fields, and loading KeyFree events. Fixed minor issues with Max Money feature.

New issues: Mod Menu descriptions are displaced. Not sure how to fix it.

**Comment by TGEnigma** [comment]
Move the new dlg/sels to the bottom of the msg file or else you'll offset any hardcoded ids.

**Comment by TGEnigma** [comment]
Also, try not to reformat the entire file. It clutters the diff.

**Comment by ShrineFox** [comment]
The [latest commit](https://github.com/ShrineFox/Persona-5-Mod-Menu/commit/3704c788db94c154e628ddb0f806bab6968784fa) now includes most of these changes, manually added them to prevent formatting issues.

**Pull request closed without merging**
